garagewatch:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: garage_user
      password: "{{ env_var('GARAGE_DB_PASSWORD') }}"
      port: 5432
      dbname: garage_data
      schema: analytics
      threads: 1
    athena:
      type: athena
      s3_staging_dir: s3://garagewatch-data/athena-results/
      region_name: us-east-1
      database: garagewatch_raw
      schema: garagewatch_analytics
      threads: 1
