apiVersion: 1

datasources:
  - name: GarageDB
    type: postgres
    url: host.docker.internal:5432
    database: garage_data
    user: garage_user
    secureJsonData:
      password: ${GARAGE_DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
    editable: true
