apiVersion: 1

datasources:
  - name: GarageDB
    type: postgres
    url: host.docker.internal:5432
    database: garage_data
    user: garage_user
    secureJsonData:
      password: ${GARAGE_DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
    editable: true
  - name: GarageAthena                                                                                                              
    type: grafana-athena-datasource
    isDefault: false
    editable: true                                                                                                                  
    jsonData:
      authType: keys                                                                                                                
      defaultRegion: us-east-1
      catalog: AwsDataCatalog
      database: garagewatch_analytics                                                                                                     
      workgroup: primary
      outputLocation: s3://garagewatch-data/athena-results/                                                                         
    secureJsonData:
      accessKey: ${ATHENA_ACCESS_KEY_ID}                                                                                            
      secretKey: ${ATHENA_SECRET_ACCESS_KEY}   